"""Correctness tests for move.py.

perft(1) and perft(2) below are hand-derived from the rules by reasoning
through the starting position move-by-move (not generated by running this
code), then cross-checked against the implementation -- see the perft(2)
divide breakdown in conversation history for the case-by-case reasoning.
perft(3) has no independent derivation; it's a regression baseline only.
"""

import numpy as np

from src.board_encoder import initial_board, piece_code
from src.move import Move, apply_move, checkmate, is_in_check, legal_moves, stalemate


def perft(board, color, depth):
    if depth == 0:
        return 1
    total = 0
    for move in legal_moves(board, color):
        total += perft(apply_move(board, move), 'b' if color == 'w' else 'w', depth - 1)
    return total


def test_perft_1_matches_both_colors():
    # 5 pawn pushes + 2 knight moves; every other piece is blocked by its
    # own pawn wall. Setup is symmetric, so both colors give the same count.
    board = initial_board()
    assert perft(board, 'w', 1) == 7
    assert perft(board, 'b', 1) == 7


def test_perft_2():
    assert perft(initial_board(), 'w', 2) == 53


def test_perft_3_regression_baseline():
    assert perft(initial_board(), 'w', 3) == 506


def test_check_limits_legal_moves_to_escaping_king():
    board = np.zeros((5, 5), dtype=np.int8)
    board[0, 4] = piece_code('K', 'w')  # white king e1
    board[4, 4] = piece_code('R', 'b')  # black rook e5, pins the e-file
    board[4, 0] = piece_code('K', 'b')  # black king a5

    assert is_in_check(board, 'w')
    assert set(legal_moves(board, 'w')) == {
        Move((0, 4), (0, 3)),
        Move((0, 4), (1, 3)),
    }


def test_promotion_generates_all_four_choices():
    board = np.zeros((5, 5), dtype=np.int8)
    board[3, 2] = piece_code('P', 'w')  # one step from promoting
    board[0, 0] = piece_code('K', 'w')
    board[4, 0] = piece_code('K', 'b')

    promo_moves = [m for m in legal_moves(board, 'w') if m.from_sq == (3, 2)]
    assert {m.promo for m in promo_moves} == {'Q', 'R', 'B', 'N'}
    assert all(m.to_sq == (4, 2) for m in promo_moves)


def test_checkmate_corner():
    # White Ka1 boxed in: black Ra1-file gives check, black king b3 covers
    # the two escape squares the rook's file doesn't already cover.
    board = np.zeros((5, 5), dtype=np.int8)
    board[0, 0] = piece_code('K', 'w')
    board[4, 0] = piece_code('R', 'b')
    board[1, 2] = piece_code('K', 'b')

    assert legal_moves(board, 'w') == []
    assert checkmate(board, 'w')
    assert not stalemate(board, 'w')


def test_stalemate_classic():
    # White Ka1, black Qc2, black king out of the way: all three king
    # escape squares are covered but the king itself isn't attacked.
    board = np.zeros((5, 5), dtype=np.int8)
    board[0, 0] = piece_code('K', 'w')
    board[1, 2] = piece_code('Q', 'b')
    board[4, 4] = piece_code('K', 'b')

    assert legal_moves(board, 'w') == []
    assert not is_in_check(board, 'w')
    assert stalemate(board, 'w')
    assert not checkmate(board, 'w')
